version: '3.3'
services:
  react:
    build: ./react/.
    ports:
      - "8080:80"
      - "8485:8485"
    volumes:
      # - ./react/build:/var/www
      - ./react/nginx.conf:/etc/nginx/nginx.conf
      - ./react/configs:/etc/nginx/conf.d
  eapi:
    build: ./eapi/.
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/fixtures
      - ./mongo/mongo_import.sh:/docker-entrypoint-initdb.d/mongo_import.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mySecretPW
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mySecretPW
  lb:
    build:
      context: ./nginx-plus-nap
    restart: always
    ports:
      - 80:80
      - 85:85
      - 81:8485
    volumes:
    - ./nginx-plus-nap/configs:/etc/nginx/conf.d
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      # - ./locust:/mnt/locust
      - ./locust/locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py -H http://lb