- name: Configure Beacon
  hosts: control
  gather_facts: false
  connection: local

  vars:
    csAPI: "https://api.cloudservices.f5.com"
    ingestAPI: "https://ingestion.ovr.prd.f5aas.com:50443"

  vars_files:
    - vars.yaml


  tasks:

    - set_fact:
        beacon_un: "{{ lookup('env', 'BEACON_UN') }}"
        beacon_pw: "{{ lookup('env', 'BEACON_PW') }}"
        beacon_acct: "{{ lookup('env', 'BEACON_ACCT') }}"

    - name: Get Beacon Auth
      uri:
        url: "{{csAPI}}/v1/svc-auth/login"
        method: POST
        body_format: json
        body:
          username: "{{ beacon_un }}"
          password: "{{ beacon_pw }}"
      register: authtoken
      delegate_to: localhost

    - name: Delete Ingest Token
      uri:
        url: "{{csAPI}}/beacon/v1/telemetry-token/bacon_token"
        method: DELETE
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body_format: json
      register: deleteToken
      delegate_to: localhost

    - name: Delete Apps
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body:
          action: remove
          declaration:
            - application:
                name: "{{ lookup('file', item) | from_json | json_query('declaration[0].application.name') }}"
        status_code: 202
      register: deleteApps
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/apps/*', wantlist=True) }}"

    - name: Delete Insights
      uri:
        url: "{{csAPI}}/beacon/v1/insights/{{ lookup('file', item) | from_json | json_query('title') | urlencode()}}"
        method: DELETE
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
      register: deletedInsights
      delegate_to: localhost
      loop: "{{ lookup('fileglob', 'beacon/insights/*', wantlist=True) }}"


    - name: Delete HTTP Monitors
      uri:
        url: "{{csAPI}}/beacon/v1/declare"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        body:
          action: remove
          declaration:
            - monitor:
                name: "{{ item.name }}"
        status_code: 202
      register: deleteMonitors
      delegate_to: localhost
      loop: "{{ http_monitors }}"


    - name: Delete Sources
      uri:
        url: "{{csAPI}}/beacon/v1/sources/{{item.type | urlencode()}}/{{item.name | urlencode()}}"
        method: DELETE
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ authtoken.json.access_token }}"
          X-F5aas-Preferred-Account-Id: "{{ beacon_acct }}"
        status_code: 200
      register: deleteSources
      delegate_to: localhost
      loop:
        - name: bacon_east
          type: telegraf
        - name: bacon_west
          type: telegraf
        - name: "Bacon East"
          type: monitor
        - name: "Bacon West"
          type: monitor

    - debug:
        msg: "{{ deleteSources }}"